### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [johyemtol/C202309#2]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/studentGrade
    - Warning: implicit declaration of function 'printSRanks' is invalid in C99 [line 91]
        - printSRanks 함수가 없습니다. 호출하는 함수 이름을 한 번 더 확인해주세요.

**Comment by johyemtol** [comment]
#2 수정완료했습니다
